/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eContractSol from "./e-contract.sol";
export type { eContractSol };
import type * as mtkSol from "./mtk.sol";
export type { mtkSol };
